---
- name: Déploiement DEV - Application Python depuis Git
  hosts: dev
  vars_files:
    - ../vault.yml
  tasks:
    - name: Test ping avec mot de passe Vault
      ping:
      vars:
        ansible_password: "{{ dev_password }}"

    - name: Installer Git, Python et pip
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - python3
        - python3-pip

    - name: Créer le répertoire de l'application
      file:
        path: /opt/app-dev
        state: directory

    - name: Cloner le dépôt depuis GitHub
      git:
        repo: 'https://github.com/blackpanther10/EXO.git'  # Ton repo
        dest: /opt/app-dev
        version: dev  # Branche dev
        force: yes

    - name: Installer les dépendances Python (si requirements.txt)
      pip:
        requirements: /opt/app-dev/requirements.txt
      ignore_errors: yes

    - name: Exécuter le script Python
      command: python3 main.py
      args:
        chdir: /opt/app-dev/app
      register: python_output

    - name: Afficher le résultat de main.py
      debug:
        msg: "Python script executed! Output:\n{{ python_output.stdout }}"

    - name: Créer un fichier de confirmation
      copy:
        content: "Déploiement DEV Python effectué avec succès le {{ ansible_date_time.iso8601 }}"
        dest: /opt/app-dev/deploy.log
